version: '3.8'

services:
  webapp:
    build:
      context: ./42sh_tester
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./42sh_tester/public:/app/public   # Share public folder
      - /app/node_modules                  # Avoid overwriting node_modules
    stdin_open: true
    tty: true

  scheduler:
    build:
      context: ./test_env
      dockerfile: Dockerfile
    volumes:
      - ./42sh_tester/public:/app/public   # Shared output directory
    ports:
      - "4000:4000"                        # WebSocket port
