version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules                  # Avoid overwriting node_modules
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules                  # Avoid overwriting node_modules
      - ./backend/data:/usr/src/app/data:z   # Shared volume for data directory
      - ./backend/tester_src:/usr/src/app/tester_src:z #Shared volume for tester source
    stdin_open: true
    tty: true
